### ISSUE TITLE
Doesn't work in some scopes

### ISSUE THREAD

**Issue by keoshi** [merriam/timestamp#1]
Was wondering if you could help me understand why this script only works on some scopes and not others. For example, can't get this to work in Markdown — where it would be really useful for me —, but works in SCSS. Here are a few examples:

### Works in

- Plaintext
- SCSS
- Javascript
- AppleScript
- Objective-C

### Doesn't work

- Markdown
- HTML
- PHP

Is there a way to override Sublime's default tab behavior on certain scopes?

Thanks in advance!

**Comment by merriam** [comment]
Sorry, this work is abandoned.  Really, it was only a few lines of code.

**Comment by keoshi** [comment]
@merriam cool, no worries.
